Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -25,19 +25,28 @@ jobs:
     - uses: actions/checkout@v4
     - name: Clone external repository
       run: git clone https://github.com/karttofer/vnzlahistory-sper.git
+
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
-        if [ -f vnzlahistory-sper/requirements.txt ]; then pip install -r vnzlahistory-sper/requirements.txt; fi
+        if [ -f vnzlahistory-sper/requirements.txt ]; then
+          pip install -r vnzlahistory-sper/requirements.txt
+        else
+          echo "requirements.txt not found"
+          exit 1
+        fi
+
     - name: Lint with flake8
       run: |
         flake8 vnzlahistory-sper --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 vnzlahistory-sper --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
     - name: Test with pytest
       run: |
-        python vnzlahistory-sper/main.py  # Asegúrate de que el archivo main.py está en la ruta correcta
+        python vnzlahistory-sper/main.py 
